export type DrillCategory = "Ball Handling"|"Shooting"|"Finishing"|"Defense"|"Footwork"|"Speed & Agility"|"Passing"|"Rebounding"|"Decision-Making / Live Play"|"Transition / Team"|"Conditioning"|"Warm-Up / Movement Prep"|"Strength / Athletic Development"|"Competition / Games";
export type MeasurementType = "makes-attempts"|"time"|"reps"|"distance"|"percentage"|"none";
export type DrillDefinition={name:string;primaryCategory:DrillCategory;tags:DrillCategory[];measurable?:boolean;measurementType?:MeasurementType;variations?:string[]};
const d=(name:string,primaryCategory:DrillCategory,tags:DrillCategory[]=[primaryCategory],measurable=false,measurementType:MeasurementType="none",variations:string[]=[]):DrillDefinition=>({name,primaryCategory,tags:[...new Set(tags)],measurable,measurementType,variations});
const names=(category:DrillCategory, values:string[])=>values.map(name=>d(name,category));
export const shootingLocations=["Right Corner","Right Short Corner","Right Wing","Right Elbow","Top / Top of Key","Left Elbow","Left Wing","Left Short Corner","Left Corner","Baseline","Free-Throw Line"];
export const masterDrills:DrillDefinition[]=[
...names("Ball Handling",["Pound Dribble","Low Dribble","Waist-Level Dribble","Alternating Low Pounds","Low → Middle → High Control","Crossover","Between-the-Legs","Behind-the-Back","Pound → Crossover","Pound → Between","Pound → Behind","Pound → Cross → Between → Behind","Cross → Between","Cross → Between → Behind Combo","Pound → Shift","Cross → Shift","Between → Shift","Moving Low Dribble","Moving Crossover","Moving Between-the-Legs","Retreat → Advance","Full-Court Dribble","Full-Court Dribble Sprints","Speed Dribbling","Change-of-Pace Dribbling","In-and-Out","In-and-Out → Sprint","Crossover → Sprint","Crossover → Attack","Crossover → Drive","Behind-the-Back → Drive","Behind-the-Back → Spin","Double Crossover","Zig-Zag Crossover","Zig-Zag Cone Dribbling","Tight-Cone Dribbling","Cone Weave","Two-Ball Pounds","Two-Ball Alternating","Two-Ball Crossover","Zig-Zag Two-Ball Dribble","Ball Protection Dribbling","Pressure Dribbling","1-on-1 Pressure Ball Handling","Defender Reaction Dribble","Tennis-Ball Reaction Dribble","Figure-8 Dribble","Figure-8 No-Dribble Ball Transfer","Ball Slaps","Freestyle Dribbling","Skips w/ Pound Dribble","Skips w/ V Dribble","2 Slow, 2 Quick — Between/Cross","PG Combo","Cross-Step Punch","Lateral Punch","Dribble Challenge — Pound → Cross → Between → Cross"]),
d("Catch-and-Shoot","Shooting",["Shooting"],true,"makes-attempts",shootingLocations),d("One-Dribble Pull-Up","Shooting",["Shooting"],true,"makes-attempts",shootingLocations),
...names("Shooting",["Form Shooting","Catch-and-Shoot 3","Spot Shooting","Five-Spot Shooting","Movement Shooting","Pump Fake → One-Dribble Pull-Up","Chair Handoff → One-Dribble Pull-Up","Free Throws","Pressure Free Throws","3-Point Contest","Shooting Challenge","5-in-a-Row Shooting"]),d("Full-Court Shooting","Shooting",["Shooting","Conditioning"],true,"makes-attempts"),
...names("Finishing",["Mikan Drill","Reverse Mikan","Layups","Different-Foot Finishes","Different-Angle Finishes","One-Foot Finish","Two-Foot Finish","Power Finish","Power Layup","Power Layup w/ Contact Pad","Contact Finish","Contact Layups","Reverse Layup","Reverse Layup Repetition Drill","Euro Step","Floater","Transition Finish","Baseline Finish","Middle Finish","Same-Side Finish","Opposite-Side Finish","Inside-Foot Finish","Outside-Foot Finish","Stride-Stop Finish","Jump-Stop Finish","Finishing Gauntlet","Last Rep = Best Rep","Live Read Finishing","Handle → Sprint → Score","Layup Elimination"]),d("Pit Drill","Defense",["Defense","Finishing","Conditioning"]),
...names("Defense",["Kobe Drill","30-Second Drill","Hustle Drill","3-Cone Closeout Drill","Shell Drill","Baseline Help & Recovery","1-on-1 Full-Court Pressure","Trap & Rotate","Box-Out War","Loose Ball Hustle Drill","2-on-1 Fast Break Defense","3-on-2 Fast Break Defense","Late-Game Defensive Possessions","Score-Stop-Score","Mirror Drill","Defensive Slides","Defensive Slide Zig-Zag","Lateral Push","Crossover Recovery","Hip Turn","Drop Step","Closeout","Rear Contest","Closeout → Backpedal","Closeout → Sprint → Chop → Hand Up","Closeout & Reaction","Defensive Recovery","Defender Mirror / Shadow","1-on-1 Shadowing","Live Defense","Coach Point Left/Right Reaction","Offensive Drive Left/Right Cut-Off","Reaction Light Defensive Cut","Four-Light Random Cut Drill","Attack-Closeout 1-on-1","Cone Crossover vs Defender Leverage"]),
...names("Footwork",["Step-Over-Step → Step-Back","Two-Foot Hop Forward/Back","Two-Foot Side-to-Side Hops","Ali Shuffle","Jab Step","Split Step","Drop","Hip Swivel","Punch Drag","Cross Jab","Inside-Out Step","Lateral Push","Jump Stop","Jump Stop → Pivot","Deceleration","First Step","Cutting","Stopping","Acceleration","Change of Direction","Crossover Step","Hip Turn","45° Cut","Braking / Hard Stop"]),
...names("Speed & Agility",["Lane Agility Drill","Suicide Sprints","Baseline-to-Baseline Sprints","Full-Court Sprints","3/4-Court Sprint","Sprint Backpedals","Defensive Slide Relay","Quick Feet → Sprint","Sprint Starts","Agility Ladder","Reaction Drill","Tennis-Ball Reaction","Reaction Lights","Lateral Acceleration","Linear Acceleration","First-Step Speed","Change-of-Direction Drill"]),d("Progressive Full-Court Sprint","Speed & Agility",["Speed & Agility","Conditioning"],true,"time",["25%","50%","75%","100%"]),
...names("Passing",["2-Man Passing","3-Man Weave","3-Man Weave w/ Corner Touch","3-Man Advance","Corner Pressure Passing","2-on-2 Keep Away","Moving-Target Passing","Transition Passing","Full-Court Passing Relay","No-Look Passing","Off-Hand Passing","Drive-and-Kick Passing","Pick-and-Roll Passing Reads","Chest Pass","Bounce Pass","One-Hand Chest Pass","One-Hand Bounce Pass","Stagger-Stance Overhead Pass","Behind-the-Back Pass"]),
d("Rebound & Outlet","Decision-Making / Live Play",["Decision-Making / Live Play","Rebounding","Passing","Transition / Team"]),...names("Rebounding",["Box-Out War","Live Box-Out","Closeout → Rebound → Outlet"]),
...names("Decision-Making / Live Play",["1-on-1","2-on-1","2-on-2","3-on-2","3-on-3","Continuous 3-on-3","3-on-3 Advantage","1-on-1 — 3 Dribbles Max","3-Second Scoring Drill","Live Read Finishing","Closeout Attack","Transition Decision-Making","Pick-and-Roll Reads","Advantage / Disadvantage","Create an Advantage","Keep the Advantage","Use the Advantage","Score-Stop-Score","Late-Game Situations","King of the Court","Advantage Tournament"]),
...names("Transition / Team",["3-Man Weave","3-Man Weave w/ Corner Touch","3-Man Advance","3-Lane Fast Break","2-on-1 Transition","3-on-2 Transition","3-on-2 → 2-on-1 Continuous","Full-Court Advantage / Disadvantage","Transition Finishing","Full-Court Scrimmage","3-on-3 Half-Court","2-on-2","1-on-1 Half-Court","1-on-1 Full-Court","Shell Drill","Pick-and-Roll","Backdoor Cuts","Defensive Switches"]),
...names("Conditioning",["11s","Moore Hearts","Suicide Sprints","Baseline-to-Baseline Sprints","Full-Court Sprint Intervals","Defensive Slide Relay","Full-Court Dribble Sprints","Handle → Sprint → Score","Make/Miss Conditioning","Pressure Free Throws — Miss = Down-and-Back","Team Relay Races","Gauntlet / Obstacle Course","Push-Up & Plank Challenge"]),
...names("Warm-Up / Movement Prep",["Bodyweight Squats","Lateral Lunges","QKC","Quad Pull","Knee Hug","Calf Raise","Toe Touches","Sprint Backpedals","Knee Pulls","Quad Pulls","Tiptoe Walks","Low Scoops","High Knees","Butt Kicks","Frankensteins","Walking Lunge + Rotation","Pogo Hops","Defensive Slides","Closeout → Backpedal","Jump Stop → Pivot","Quick Feet → Sprint","Arm Circles","Hip Openers","Hamstring Kicks"]),
...names("Strength / Athletic Development",["Jump Squats","Pause Squat Jumps","Tempo Squats","Pogo Jumps / Ankle Hops","Wall Jumps","Tuck Jumps","Split-Squat Jumps","Split-Stance Snap Jumps","Vertical Jumps","Broad Jumps","Banded Broad Jumps","Standing Triple Jump","Skater Bounds","Lateral Bounds","Lateral Bound → Stick","Single-Leg Lateral Jumps","Reverse Lunge → Jump","Step-Up Jumps","Seated Box Jump","Kneeling → Broad Jump","Box Jump — Max Height","Depth Drop → Stick","Depth Drop → Vertical","Depth Jump → Vertical","Depth Jump → Sprint","Single-Leg Depth Drop → Hop","Snap Down → Vertical","Snap Down → Tuck Jump","Squats","Reverse Lunges","Lateral Lunges","Glute Bridges","Calf Raises","Push-Ups","Incline Push-Ups","Assisted Pull-Ups","Rows","Plank","Dead Bug","Pallof Press","Partner Resistance Pushes","Resistance-Band Leg Work","Wall-Sit March","Wall Sits","Medicine-Ball Passes"]),
...names("Competition / Games",["King of the Court","3-Point Contest","Shooting Challenge","Spot Shooting Contest","Free-Throw Contest","Dribble Knockout","Layup Elimination","Team Relay Race","Advantage Tournament","Parent vs. Kids Game","1-on-1 Competition","2-on-2 Competition","3-on-3 Competition"])
];
// Collapse repeated names into one permanent drill and merge categories/tags.
export const drillLibrary=[...masterDrills.reduce((map,item)=>{const key=item.name.toLowerCase();const existing=map.get(key);if(!existing)map.set(key,item);else map.set(key,{...existing,tags:[...new Set([...existing.tags,...item.tags])]});return map},new Map<string,DrillDefinition>()).values()];
export const drillCategories=[...new Set(drillLibrary.flatMap(x=>x.tags))];
