"use client";
import {useEffect,useMemo,useState} from "react";
import {drillLibrary} from "@/domain/drills/master-drill-library";
import "./practice-plans.css";
type Drill={title:string;canonical?:string;notes:string;dose:string}; type Section={id:string;title:string;drills:Drill[]}; type Plan={id:string;name:string;date:string;group:string;duration:string;location:string;focus:string;notes:string;sections:Section[]};
const K="tt-practice-plans-v1"; const fresh=():Plan=>({id:crypto.randomUUID(),name:"New Practice Plan",date:new Date().toISOString().slice(0,10),group:"",duration:"90 minutes",location:"",focus:"",notes:"",sections:[{id:crypto.randomUUID(),title:"Warm-Up",drills:[]}]});
export default function Page(){const[plans,setPlans]=useState<Plan[]>([]),[plan,setPlan]=useState<Plan|null>(null),[q,setQ]=useState(""),[target,setTarget]=useState(""),[custom,setCustom]=useState("");
useEffect(()=>{try{setPlans(JSON.parse(localStorage.getItem(K)||"[]"))}catch{}},[]); const hits=useMemo(()=>q?drillLibrary.filter(d=>d.name.toLowerCase().includes(q.toLowerCase())||d.tags.some(t=>t.toLowerCase().includes(q.toLowerCase()))).slice(0,12):[],[q]);
const persist=(x:Plan[])=>{setPlans(x);localStorage.setItem(K,JSON.stringify(x))}; const save=()=>{if(plan)persist([plan,...plans.filter(p=>p.id!==plan.id)])}; const duplicate=()=>{if(plan){const x={...plan,id:crypto.randomUUID(),name:plan.name+" Copy"};setPlan(x);persist([x,...plans])}};
const add=(name:string,canonical?:string)=>{if(!plan||!target)return;setPlan({...plan,sections:plan.sections.map(s=>s.id===target?{...s,drills:[...s.drills,{title:name,canonical,notes:"",dose:""}]}:s)});setQ("");setCustom("");setTarget("")};
if(!plan)return <main className="players-shell"><header className="players-header"><div><p className="eyebrow">PRACTICE PLANS</p><h1>Plan Builder</h1><p className="support-copy">Team, small-group and camp plans stay separate from player history.</p></div><button className="primary-button compact-primary" onClick={()=>setPlan(fresh())}>+ Create Practice Plan</button></header><section className="player-list-section">{plans.length?plans.map(p=><button className="practice-plan-card" key={p.id} onClick={()=>setPlan(p)}><strong>{p.name}</strong><span>{p.group||"No group"} · {p.date} · {p.duration}</span></button>):<p className="empty-state">No standalone practice plans yet.</p>}</section></main>;
return <main className="players-shell practice-builder"><header className="players-header no-print"><div><button className="back-link button-link" onClick={()=>setPlan(null)}>← Practice Plans</button><p className="eyebrow">STANDALONE PRACTICE PLAN</p><h1>{plan.name}</h1></div><div className="practice-actions"><button onClick={save}>Save</button><button onClick={duplicate}>Duplicate</button><button className="primary-button compact-primary" onClick={()=>window.print()}>Export PDF</button></div></header><section className="practice-print-header"><p>THAT&apos;S TUFF PERFORMANCE TRAINING</p><h1>{plan.name}</h1><strong>Your Game. Our Focus.</strong></section>
<section className="player-create-card practice-meta">{([["Practice name","name"],["Date","date"],["Team / group","group"],["Duration","duration"],["Location","location"],["Focus","focus"]] as const).map(([label,k])=><label key={k}>{label}<input type={k==="date"?"date":"text"} value={plan[k]} onChange={e=>setPlan({...plan,[k]:e.target.value})}/></label>)}<label className="wide">Coach notes<textarea value={plan.notes} onChange={e=>setPlan({...plan,notes:e.target.value})}/></label></section>
<section className="practice-sections">{plan.sections.map((s,si)=><article className="player-create-card" key={s.id}><div className="practice-section-title"><b>{si+1}</b><input value={s.title} onChange={e=>setPlan({...plan,sections:plan.sections.map(x=>x.id===s.id?{...x,title:e.target.value}:x)})}/><button className="no-print" onClick={()=>setPlan({...plan,sections:plan.sections.filter(x=>x.id!==s.id)})}>Remove</button></div>{s.drills.map((d,di)=><div className="practice-drill" key={di}><strong>{d.title}{d.canonical&&<small> · Library</small>}</strong><input placeholder="Time / reps / makes" value={d.dose} onChange={e=>setPlan({...plan,sections:plan.sections.map(x=>x.id===s.id?{...x,drills:x.drills.map((z,i)=>i===di?{...z,dose:e.target.value}:z)}:x)})}/><input placeholder="Notes / coaching cues" value={d.notes} onChange={e=>setPlan({...plan,sections:plan.sections.map(x=>x.id===s.id?{...x,drills:x.drills.map((z,i)=>i===di?{...z,notes:e.target.value}:z)}:x)})}/></div>)}<button className="ghost-button no-print" onClick={()=>setTarget(s.id)}>+ Add Drill</button>{target===s.id&&<div className="drill-picker no-print"><input autoFocus placeholder="Search Drill Library..." value={q} onChange={e=>setQ(e.target.value)}/>{hits.map(d=><button key={d.name} onClick={()=>add(d.name,d.name)}><strong>{d.name}</strong><span>{d.primaryCategory}{d.measurable?" · "+d.measurementType:""}</span></button>)}<div className="custom-drill"><input placeholder="Custom / improvised drill" value={custom} onChange={e=>setCustom(e.target.value)}/><button disabled={!custom.trim()} onClick={()=>add(custom.trim())}>Add custom</button></div></div>}</article>)}<button className="ghost-button no-print" onClick={()=>setPlan({...plan,sections:[...plan.sections,{id:crypto.randomUUID(),title:"New Section",drills:[]}]})}>+ Add Section</button></section></main>}
